### ISSUE TITLE
README broken link

### ISSUE THREAD

**Issue by yairEO** [Simonwep/intl-demo#6]
Hi, wanted to report a broken link:
```
<a align="center" href="https://simonwep.github.io/intl-demo" target="_blank">
    <img src="https://user-images.githubusercontent.com/30767528/71321460-ed7a8200-24b9-11ea-8c62-e699f5b2a9d4.png" alt="for real">
</a>
```

**Comment by Simonwep** [comment]
Looks good to me? 🤔
![image](https://user-images.githubusercontent.com/30767528/102712626-ed76b300-42c2-11eb-84bd-18d1b79d10cd.png)

**Comment by yairEO** [comment]
You probably made private somehow. This is very rare to see, and this means you didn't configure something  correctly in your repo:

![image](https://user-images.githubusercontent.com/845031/102888967-6eb87c00-4462-11eb-9d34-2b13241c0f92.png)

**Comment by Simonwep** [comment]
Whoops you're right, I moved it to my own VPS: https://intl.reinisch.io, I'll update it!
